FROM node:lts-alpine AS builder
WORKDIR /app

COPY package*.json ./
RUN export CI=true && \
  npm install --only=prod

COPY . ./

RUN npm run build

FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/build /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]
